import "./globals.css";
import Navbar from "@/ui/navbar/Navbar";
import Footer from "@/ui/footer/Footer";
import BackgroundEffects from '@/ui/background/BackgroundEffects';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
      {/* <BackgroundEffects /> */}

        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
